project:
  type: website

website:
  title: "on-data"
  site-url: https://m-01101101.github.io/on-data/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



